---
- name: install memcached package
  apt: pkg=memcached state=installed
  notify: memcached update-rc.d

- name: add /etc/memcached.conf
  template: >
    src=etc-memcached.conf.j2
    dest=/etc/memcached.conf
    owner=root group=root mode=0644
  notify: memcached restart

- name: edit /etc/default/memcached
  lineinfile: >
    dest=/etc/default/memcached
    regexp="^ENABLE_MEMCACHED\=(.+)"
    line='ENABLE_MEMCACHED=yes'
    state=present

- name: ensure memcached started
  service: name=memcached state=started enabled=yes
